# Generated by Django 2.2.2 on 2019-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='arc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
